/* eslint-disable class-methods-use-this */
import { Model, DataTypes } from "sequelize";
import db from "../../db/db";
import PostVote from "./PostVote";

export interface PostAttributesInterface {
  title: string;
  body: string;
  authorId: number;
  authorName: string;

  // Optional values, not required to add when creating a post
  edited?: boolean;

  // below are automatically generated by the db
  id?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

class Post extends Model<PostAttributesInterface> {
  constructor(init?: Partial<Post>) {
    super();
    Object.assign(this, init);
  }
}

Post.init(
  {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      unique: true,
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: false,
    },
    authorId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    authorName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    body: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
    edited: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  },
  {
    tableName: "Posts",
    freezeTableName: true, // no alter
    sequelize: db,
  }
);

Post.hasMany(PostVote, { foreignKey: "postId" });

export default Post;
