// vote is going to have post id, comment id, or reply id, and the user who voted
// if they upVoted a comment, the post id and reply id will be null. This way we only flag the thing they voted

import { Model, DataTypes } from "sequelize";
import db from "../../db/db";

export interface PostVoteAttributesInterface {
  upvote?: boolean;
  downvote?: boolean;
  userId: number;
  postId: number;
  userName: string;
  createdByTest?: boolean;

  // below are automatically generated by the db
  id?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

class PostVote extends Model<PostVoteAttributesInterface> {
  constructor(init?: Partial<PostVote>) {
    super();
    Object.assign(this, init);
  }
}

PostVote.init(
  {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      unique: true,
    },
    userName: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    userId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    postId: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    upvote: {
      type: DataTypes.BOOLEAN,
      allowNull: true,
      defaultValue: null,
    },
    downvote: {
      type: DataTypes.BOOLEAN,
      allowNull: true,
      defaultValue: null,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    createdByTest: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false,
    },
  },
  {
    tableName: "PostVotes",
    freezeTableName: true, // no alter
    sequelize: db,
  }
);

export default PostVote;
