# Update

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Tests

    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x

        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci
        env:
          PGUSER: ${{ secrets.PGUSER }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGPORT: ${{ secrets.PGPORT }}
          PORT: ${{ secrets.PORT }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          BCRYPT: ${{ secrets.BCRYPT }}

      - name: Run Tests
        run: npm test
        env:
          PGUSER: ${{ secrets.PGUSER }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGPORT: ${{ secrets.PGPORT }}
          PORT: ${{ secrets.PORT }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          BCRYPT: ${{ secrets.BCRYPT }}
